import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex ">
        <Sidebar />
        <div className="w-full">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
